language: java
jdk:
- oraclejdk8
services:
- mongodb
script:
- mvn clean install
notifications:
  slack:
    secure: oBpYzB4XVpCsezsTVZW7MfOlmL56lZoTJGaPl35TeXbrSPr5tAfQ+3xjjDT6GMAvuLZRsduHftrshdNdhy+GPRFWjcoiQ3sINPd/nnAaBtiHCeSp85bNjz3bqftw29UesoAFgPb0Cy2ZlASL9P0xB9iHj4LFe5BbHlm6MQBHd0ezpL02LG9X5UH0urRUDbouX2dF0mVylMulLeqoJbPcC6VfDFXU0il9K/mjJPiBGnlzRLK4ZMOvjnDj1VlHfmzdJOvwtFT/hrqspaoMw3/hQizGg6jvFFfS5zh9DQZc/DUxHtzkSxlvSX+Yrkz3VPKRX2vRyxmuxUTV+XVn9FOYWvtsRK+un2eA5DKRuVUDDibUWelCZHhUSZt/ubjrr6MSMYyHFjaRJftwtc7x/5JWCHR7hr+TjrcPH4fcPWFlYXlv2EnVjbzHx/Ep9F43ZKZmISNpBWrQKsIHiJ0x/99b9xWWBSp0IugeA3GayhIFFde2tKrmhlQdv++MqgQzfD2QEpz0xkgCpG81a3Gs+n9Ivx6OIfu0bHwdi930qU0awWTRDe9Lb9+wEPsyTbtT6lB3SZzn7oE8klNFnFoGYPm8AiSMEeUwAh96MXicoLrUPCjybqpSBKeeuCFwqX3ZvTj5KyR3RdhBG0ONeVABPC9OtEl1G69ELp5g9tW7XtWU4Is=
